[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["Kyle Strohbeck <kstrohbeck@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.1"
rayon = "1.5.0"
num = "0.3.1"
itertools = "0.9.0"
